# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  release:
    types: [published]
  pull_request_target:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        architecture: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.architecture }}
      run: go build -o viam-appliedmotion -v .

    - name: Package
      run: tar -zcf viam-appliedmotion-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz viam-appliedmotion
    
    - uses: actions/upload-artifact@v3
      with:
        name: viam-appliedmotion-${{ matrix.os }}-${{ matrix.architecture }}
        path: viam-appliedmotion-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code
  #     if: github.event_name != 'pull_request_target'
  #     uses: actions/checkout@v3

  #   - name: Check out PR branch code
  #     if: github.event_name == 'pull_request_target'
  #     uses: actions/checkout@v3
  #     with:
  #       ref: ${{ github.event.pull_request.head.sha }}
  #       fetch-depth: 0

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.20'
  #   - name: Test
  #     run: go test -v ./...

  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        architecture: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}
    needs: [build]
    if: github.event_name == 'release'
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - uses: actions/download-artifact@v3
      with:
        name: viam-appliedmotion-${{ matrix.os }}-${{ matrix.architecture }}
    - name: Upload
      uses: viamrobotics/upload-module@main
      with:
        module-path: viam-appliedmotion-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz
        namespace: viam-labs
        platform: ${{ matrix.os }}/${{ matrix.architecture }}
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
