# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  release:
    types: [published]
  pull_request_target:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build linux arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -o viam-appliedmotion -v .

    - name: Package
      run: tar -zcf viam-appliedmotion.tar.gz viam-appliedmotion
    
    - uses: actions/upload-artifact@v3
      with:
        name: viam-appliedmotion
        path: viam-appliedmotion.tar.gz

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code
  #     if: github.event_name != 'pull_request_target'
  #     uses: actions/checkout@v3

  #   - name: Check out PR branch code
  #     if: github.event_name == 'pull_request_target'
  #     uses: actions/checkout@v3
  #     with:
  #       ref: ${{ github.event.pull_request.head.sha }}
  #       fetch-depth: 0

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.20'
  #   - name: Test
  #     run: go test -v ./...

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - uses: actions/download-artifact@v3
      with:
        name: viam-appliedmotion
    - name: Upload
      uses: viamrobotics/upload-module@main
      with:
        module-path: viam-appliedmotion.tar.gz
        namespace: viam-labs
        platform: linux/arm64
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
